/*
 * Vegcord, a desktop app aiming to give you a snappier Discord Experience
 * Copyright (c) 2023 Vendicated and Vencord contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "./telemetry";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";

import { VegcordSettingsIcon } from "./components/SettingsIcon";

import SettingsUi from "./components/settings/Settings";
import { VegcordLogger } from "./logger";
import { Settings } from "./settings";
export { Settings };

VegcordLogger.log("read if cute :3");
VegcordLogger.log("Vegcord v" + VegcordNative.app.getVersion());

const SettingsPlugin = Vencord.Plugins.plugins
    .Settings as typeof import("@vencord/types/plugins/_core/settings").default;

SettingsPlugin.customEntries.push({
    key: "vegord",
    title: "Vegcord",
    panelTitle: "Vegcord Settings",
    Component: SettingsUi,
    Icon: VegcordSettingsIcon
});
