/*
 * vegord, a desktop app aiming to give you a snappier Discord Experience
 * Copyright (c) 2023 Vendicated and vegord contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./vegordEmoji.css";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "./telemetry";
import "./settingsSync";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";

import { vegordLogger } from "./logger";
import { Settings } from "./settings";
export { Settings };

vegordLogger.log("read if cute :3");
vegordLogger.log("vegord v" + vegordNative.app.getVersion());
