/*
 * Vegcord, a desktop app aiming to give you a snappier Discord Experience
 * Copyright (c) 2023 Vendicated and Vencord contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./vegordEmoji.css";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "./telemetry";
import "./settingsSync";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";

import { VegcordLogger } from "./logger";
import { Settings } from "./settings";
export { Settings };

VegcordLogger.log("read if cute :3");
VegcordLogger.log("Vegcord v" + VegcordNative.app.getVersion());
